trigger:
  batch: true
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: calqulus
      type: git
      name: Dev/app-calqulus
      ref: refs/heads/main
    - repository: pipelines
      type: github
      endpoint: qualisys
      name: Qualisys/Calqulus-Pipelines
      ref: refs/heads/main
    - repository: data
      type: git
      name: Dev/app-calqulus-test-data
      ref: refs/heads/main
    - repository: toolbelt
      type: git
      name: Dev/app-calqulus-toolbelt
      ref: refs/heads/main
    - repository: calqulus-ci
      type: git
      name: app-calqulus-ci-templates

parameters:
  - name: skipLastSuccessfulBuild
    displayName: Skip checking regressions against last successful build
    type: boolean
    default: false
  - name: useLatestPublishedCalqulus
    displayName: Use the latest published Calqulus version
    type: boolean
    default: true

extends:
  template: calqulus-steps.yml@calqulus-ci
  parameters:
    skipLastSuccessfulBuild: ${{ parameters.skipLastSuccessfulBuild }}
    useLatestPublishedCalqulus: ${{ parameters.useLatestPublishedCalqulus }}
