trigger:
  batch: true
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: calqulus-ci
      type: git
      name: Calqulus-CI-Templates

extends:
  template: calqulus-steps.yml@calqulus-ci