trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: calqulus-ci
      type: git
      name: Calqulus-CI-Templates

parameters:
- name: skipLastSuccessfulBuild
  displayName: Skip checking regressions against last successful build
  type: boolean
  default: false

extends:
  template: calqulus-steps.yml@calqulus-ci
  parameters:
    skipLastSuccessfulBuild: ${{ parameters.skipLastSuccessfulBuild }}