trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: calqulus-ci
      type: git
      name: app-calqulus-ci-templates
    - repository: calqulus-current
      type: git
      name: Dev/app-calqulus
      ref: refs/heads/main
    - repository: calqulus-reference
      type: git
      name: Dev/app-calqulus
      ref: refs/heads/main
    - repository: calqulus-last-successful
      type: git
      name: Dev/app-calqulus
      ref: refs/heads/main
    - repository: pipelines-current
      type: github
      endpoint: qualisys
      name: Qualisys/Calqulus-Pipelines
      ref: refs/heads/main
    - repository: pipelines-reference
      type: github
      endpoint: qualisys
      name: Qualisys/Calqulus-Pipelines
      ref: refs/heads/main
    - repository: pipelines-last-successful
      type: github
      endpoint: qualisys
      name: Qualisys/Calqulus-Pipelines
      ref: refs/heads/main
    - repository: toolbelt-current
      type: git
      name: Dev/app-calqulus-toolbelt
    - repository: toolbelt-reference
      type: git
      name: Dev/app-calqulus-toolbelt
    - repository: toolbelt-last-successful
      type: git
      name: Dev/app-calqulus-toolbelt

parameters:
- name: skipLastSuccessfulBuild
  displayName: Skip checking regressions against last successful build
  type: boolean
  default: false

extends:
  template: calqulus-steps.yml@calqulus-ci
  parameters:
    skipLastSuccessfulBuild: ${{ parameters.skipLastSuccessfulBuild }}