trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: calqulus-ci
      type: git
      name: Calqulus-CI-Templates
      ref: refs/heads/feature/steps-regression-tests

extends:
  template: calqulus-steps.yml@calqulus-ci