name: $[counter('c',1)]

trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: calqulus-ci
      type: git
      name: app-calqulus-ci-templates
      ref: main

extends:
  template: base-steps.yml@calqulus-ci
